export const LOGIN_STAFF_SUCCESS = "LOGIN_STAFF_SUCCESS";
export const LOGIN_STAFF_ERROR = "LOGIN_STAFF_ERROR";
export const LOGIN_STAFF_REQUEST = "LOGIN_STAFF_REQUEST";

export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_STAFF_SUCCESS = " REGISTER_STAFF_SUCCESS";
export const REGISTER_STAFF_ERROR = "REGISTER_STAFF_ERROR";
export const REGISTER_STAFF_REQUEST = "REGISTER_STAFF_REQUEST";

export const REGISTER_ADMIN_SUCCESS = " REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR";
export const REGISTER_ADMIN_REQUEST = "REGISTER_ADMIN_REQUEST";

export const EDIT_STAFF_SUCCESS = " EDIT_STAFF_SUCCESS";
export const EDIT_STAFF_ERROR = "EDIT_STAFF_ERROR";
export const EDIT_STAFF_REQUEST = "EDIT_STAFF_REQUEST";