export const CREATE_REPORT_SUCCESS = " CREATE_REPORT_SUCCESS";
export const CREATE_REPORT_ERROR = "CREATE_REPORT_ERROR";
export const CREATE_REPORT_REQUEST = "CREATE_REPORT_REQUEST";

export const GET_STAFF_SUCCESS = " GET_STAFF_SUCCESS";
export const GET_STAFF_ERROR = "GET_STAFF_ERROR";
export const GET_STAFF_REQUEST = "GET_STAFF_REQUEST";

export const ADD_PATIENT_SUCCESS = " ADD_PATIENT_SUCCESS";
export const ADD_PATIENT_ERROR = "ADD_PATIENT_ERROR";
export const ADD_PATIENT_REQUEST = "ADD_PATIENT_REQUEST";

export const ADD_MED_SUCCESS = " ADD_MED_SUCCESS";
export const ADD_MED_ERROR = "ADD_MED_ERROR";
export const ADD_MED_REQUEST = "ADD_MED_REQUEST";

export const GET_MED_SUCCESS = " GET_MED_SUCCESS";
export const GET_MED_ERROR = "GET_MED_ERROR";
export const GET_MED_REQUEST = "GET_MED_REQUEST";

export const ADD_MEDS_SUCCESS = " ADD_MEDS_SUCCESS";
export const ADD_MEDS_ERROR = "ADD_MEDS_ERROR";
export const ADD_MEDS_REQUEST = "ADD_MEDS_REQUEST";

export const GET_PATIENT_SUCCESS = " GET_PATIENT_SUCCESS";
export const GET_PATIENT_ERROR = "GET_PATIENT_ERROR";
export const GET_PATIENT_REQUEST = "GET_PATIENT_REQUEST";

export const GET_ALLDATA_SUCCESS = " GET_ALLDATA_SUCCESS";
export const GET_ALLDATA_REQUEST = "GET_ALLDATA_REQUEST";

export const GET_REPORTS_SUCCESS = " GET_REPORTS_SUCCESS";
export const GET_REPORTS_REQUEST = "GET_REPORTS_REQUEST";
